---
title: "Stat652_project_NaiveBayes"
author: "Hui Huang Netid:hy9489"
date: "3/10/2020"
output: html_document
---


## Step 2 - Prepare the data
```{r}
nbdata <- accdata2012_2014_nona %>%
  select(loan_status,loan_amnt,funded_amnt,term,int_rate,installment,home_ownership,annual_inc,verification_status,open_acc,total_pymnt)
set.seed(999)
indx <- sample(1:nrow(nbdata),as.integer(0.75*nrow(nbdata)))
nbdata_train <- nbdata[indx,]
nbdata_test <- nbdata[-indx,]

nbdata_train_labels <- nbdata[indx,1,drop = TRUE]
nbdata_test_labels <- nbdata[-indx,1,drop = TRUE]
dim(nbdata_train)
dim(nbdata_test)
dim(nbdata_train_labels)
dim(nbdata_test_labels)
```

## Step 3 – training a model on the data
```{r}
library(e1071)
library(gmodels)
nb_model <- naiveBayes(nbdata_train[,-1],as.factor(nbdata_train_labels))
summary(nb_model)
```

## Step 4 – evaluating model performance
```{r}
nb_pred <- predict(nb_model,nbdata_test[,-1])
nb_pred
CrossTable(nb_pred,nbdata_test_labels,prop.chisq = FALSE,prop.t = FALSE,prop.r = FALSE,dnn = c('predicted','actual'))
misClasificError <- mean(nb_pred != nbdata_test_labels, na.rm=TRUE)
print(paste('Accuracy',1-misClasificError))

# ROC
library(ROCR)
pr_nb <- prediction(as.numeric(nb_pred), nbdata_test_labels)
prf.nb <- performance(pr_nb, measure = "tpr", x.measure = "fpr")
plot(prf.nb)
auc <- performance(pr_nb, measure = "auc")
auc.nb <- auc@y.values[[1]]
auc.nb
```

## Step 5 - Improve model performance
```{r}

nb_model <- naiveBayes(nbdata_train[,-1],as.factor(nbdata_train_labels),laplace = 1)
nb_pred <- predict(nb_model,nbdata_test[,-1])
summary(nb_model)
#evaluate improved model
nb_pred <- predict(nb_model,nbdata_test[,-1])
CrossTable(nb_pred,nbdata_test_labels,prop.chisq = FALSE,prop.t = FALSE,prop.r = FALSE,dnn = c('predicted','actual'))
misClasificError <- mean(nb_pred != nbdata_test_labels, na.rm=TRUE)
print(paste('Accuracy',1-misClasificError))

```

